@echo off
setlocal enabledelayedexpansion

:: Read version from the file generated by build.bat
if exist "dist\version.txt" (
    set /p VERSION=<"dist\version.txt"
) else (
    echo ERROR: dist\version.txt not found. Please run build.bat first.
    exit /b 1
)

set APP_NAME=Driver_Deck
set EXE_PATH=dist\Driver Deck.exe

echo [1/4] Detected Version: %VERSION%
echo [2/4] Running Build...
call build.bat

echo [3/4] Checking GitHub CLI...
where gh >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo ERROR: GitHub CLI (gh) is not installed.
    exit /b 1
)

echo [4/4] Publishing %APP_NAME% %VERSION% to GitHub...
gh release create %APP_NAME%-%VERSION% "%EXE_PATH%" --title "%APP_NAME% %VERSION%" --notes-file GEMINI.md

if %ERRORLEVEL% equ 0 (
    echo SUCCESS: Published to GitHub!
) else (
    echo FAILED: Could not publish.
)

pause