@echo off
setlocal enabledelayedexpansion

:: Read base version from VERSION file
if exist "VERSION" (
    set /p BASE_VER=<VERSION
) else (
    echo ERROR: VERSION file not found.
    exit /b 1
)

:: Read the exact version generated by build.bat
if exist "dist\version.txt" (
    set /p VERSION=<"dist\version.txt"
) else (
    echo ERROR: dist\version.txt not found. Please run build.bat first.
    exit /b 1
)

set APP_NAME=Driver_Deck
set EXE_PATH=dist\Driver Deck.exe

echo [1/4] Detected Version: %VERSION%

:: Extract Release Notes from CHANGELOG.md for the base version
echo [2/4] Extracting Release Notes from CHANGELOG.md...
powershell -Command "$v = '%BASE_VER%'; $c = Get-Content CHANGELOG.md -Raw; if ($c -match \"## \[$v\](.*?)(?=\n## |$)\") { $matches[1].Trim() | Out-File -Encoding utf8 notes.tmp } else { 'New release' | Out-File -Encoding utf8 notes.tmp }"

echo [3/4] Checking GitHub CLI...
where gh >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo ERROR: GitHub CLI (gh) is not installed.
    exit /b 1
)

echo [4/4] Publishing %APP_NAME% %VERSION% to GitHub...
gh release create %APP_NAME%-%VERSION% "%EXE_PATH%" --title "%APP_NAME% %VERSION%" --notes-file notes.tmp

if %ERRORLEVEL% equ 0 (
    echo SUCCESS: Published to GitHub!
    del notes.tmp
) else (
    echo FAILED: Could not publish.
    if exist notes.tmp del notes.tmp
)

pause
